### ISSUE TITLE
VoidWhitelist-0.9.1b419-stable | handling click event error

### ISSUE THREAD

**Issue by nsvk13** [voidpointer0x00/VoidWhitelist#17]
Hello again! Returned to your plugin, as there is no analogues.
When manipulating in the GUI, nothing happens, and the console gives errors.
I think I heard that you are from Russia, if possible, could we continue in the на Русском языке?

```
[22:18:11 ERROR]: [VoidWhitelist] Exception while handling click event in inventory '§6Xapu3ma_', slot=21, item=WRITABLE_BOOK
voidpointer.spigot.voidwhitelist.inventoryframework.exception.UnsupportedVersionException: The server version provided is not supported
        at voidpointer.spigot.voidwhitelist.inventoryframework.util.version.Version.getVersion(Version.java:127) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at voidpointer.spigot.voidwhitelist.inventoryframework.gui.type.AnvilGui.<init>(AnvilGui.java:70) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at voidpointer.spigot.voidwhitelist.gui.InputGui.ask(InputGui.java:37) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at voidpointer.spigot.voidwhitelist.gui.ProfileScreen.onEditButtonClick(ProfileScreen.java:139) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at voidpointer.spigot.voidwhitelist.inventoryframework.gui.GuiItem.callAction(GuiItem.java:129) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at voidpointer.spigot.voidwhitelist.inventoryframework.pane.StaticPane.click(StaticPane.java:158) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at voidpointer.spigot.voidwhitelist.inventoryframework.gui.InventoryComponent.click(InventoryComponent.java:203) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at voidpointer.spigot.voidwhitelist.inventoryframework.gui.type.ChestGui.click(ChestGui.java:128) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at voidpointer.spigot.voidwhitelist.inventoryframework.gui.GuiListener.onInventoryClick(GuiListener.java:66) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor548.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:git-Pufferfish-47]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3309) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1343) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1320) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1313) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1291) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:18:16 ERROR]: [VoidWhitelist] Exception while handling click event in inventory '§6Xapu3ma_', slot=21, item=WRITABLE_BOOK
voidpointer.spigot.voidwhitelist.inventoryframework.exception.UnsupportedVersionException: The server version provided is not supported
        at voidpointer.spigot.voidwhitelist.inventoryframework.util.version.Version.getVersion(Version.java:127) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at voidpointer.spigot.voidwhitelist.inventoryframework.gui.type.AnvilGui.<init>(AnvilGui.java:70) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at voidpointer.spigot.voidwhitelist.gui.InputGui.ask(InputGui.java:37) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at voidpointer.spigot.voidwhitelist.gui.ProfileScreen.onEditButtonClick(ProfileScreen.java:139) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at voidpointer.spigot.voidwhitelist.inventoryframework.gui.GuiItem.callAction(GuiItem.java:129) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at voidpointer.spigot.voidwhitelist.inventoryframework.pane.StaticPane.click(StaticPane.java:158) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at voidpointer.spigot.voidwhitelist.inventoryframework.gui.InventoryComponent.click(InventoryComponent.java:203) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at voidpointer.spigot.voidwhitelist.inventoryframework.gui.type.ChestGui.click(ChestGui.java:128) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at voidpointer.spigot.voidwhitelist.inventoryframework.gui.GuiListener.onInventoryClick(GuiListener.java:66) ~[VoidWhitelist-0.9.1b419-stable.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor548.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:git-Pufferfish-47]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3309) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1343) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1320) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1313) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1291) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by voidpointer0x00** [comment]
Sure :)
> I think I heard that you are from Russia, if possible, could we continue in the на Русском языке?

```UnsupportedVersionException: The server version provided is not supported```

Ядро pufferfish/purpur? Какой версии (точный билд, `/version`)?

**Comment by nsvk13** [comment]
This server is running Pufferfish version git-Pufferfish-47 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 9b8cdc7 on HEAD)
You are running 15 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.

**Comment by nsvk13** [comment]
На 1.19.3 обновиться не могу из-за несовместимости некоторых плагинов.
_(там ещё почему-то ProtocolLib ругается на 1.19.3 и выше, но это не нужная информация Вам.)_

**Comment by voidpointer0x00** [comment]
Проблема была в либе GUI, обновил и исправил один edge-case с NPE [v0.9.3-stable](https://github.com/voidpointer0x00/VoidWhitelist/releases/tag/v0.9.3-stable)

**Comment by nsvk13** [comment]
Спасибо большое, за оперативную работу! Вы потрясающий.
