### ISSUE TITLE
Couldn't add a player to the whitelist

### ISSUE THREAD

**Issue by nukerash** [voidpointer0x00/VoidWhitelist#24]
[17:24:35 WARN]: [VoidWhitelist] Couldn't add a player to the whitelist
java.util.concurrent.CompletionException: java.lang.NullPointerException: expiresAt is marked non-null but is null
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.NullPointerException: expiresAt is marked non-null but is null
        at voidpointer.spigot.voidwhitelist.storage.SimpleWhitelistable.<init>(SimpleWhitelistable.java:29) ~[VoidWhitelist-1.0.0b480-stable.jar:?]
        at voidpointer.spigot.voidwhitelist.storage.MemoryWhitelistService.lambda$add$4(MemoryWhitelistService.java:109) ~[VoidWhitelist-1.0.0b480-stable.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 6 more

**Comment by voidpointer0x00** [comment]
Fixed the issue, please, test the latest build on your system and tell if it's okay for you. Works for me anyway :)
[v1.0.1](https://github.com/voidpointer0x00/VoidWhitelist/releases/tag/v1.0.1-release)

_* Didn't even use the JSON storage myself tbh_ :smile:

**Comment by nukerash** [comment]
Thanks a lot, everything works now!
